keys:
  - &laptop age15n96t74lj62gxyk2wd8ac9aew5lpfkx2l7p8u3k5hc0hcek4hejszyp48h
  - &anywhere age189v3q8quejkaz4r8u0g2aechsfk4sk3465khx35erd320rea5scq98v7er
  - &tower age1usm3v0ugducrzcwud60dda7xfnj49fdhecj7kcsfm7dzwzrzeyqq2jc2hm
creation_rules:
  - path_regex: secrets/common\.yml$
    key_groups:
      - age:
          - *laptop
          - *anywhere
          - *tower
  - path_regex: secrets/anywhere\.yml$
    key_groups:
      - age:
          - *anywhere
  - path_regex: secrets/laptop\.yml$
    key_groups:
      - age:
          - *laptop
  - path_regex: secrets/tower\.yml$
    key_groups:
      - age:
          - *tower
