# Example configuration for hosts/tower/configuration.nix
# Wire together: rustguac (gateway) + KasmVNC (personal desktop) + RustDesk (P2P) + Vault + nginx

{ config, pkgs, lib, ... }:

{
  imports = [
    # Core modules
    ./modules/nixos/rustguac
    ./modules/nixos/kasmvnc
    ./modules/nixos/vault-rustguac
    ./modules/nixos/rustdesk
    ./modules/nixos/nginx/rustguac
    ./modules/nixos/nginx/kasmvnc
  ];

  # ========================================================================
  # VAULT (dev mode for testing - CHANGE FOR PRODUCTION!)
  # ========================================================================
  services.vault-rustguac = {
    enable = true;
    mode = "dev";  # "dev" for testing, "ha" for production
    address = "127.0.0.1";
    port = 8200;
    devRootToken = "rustguac-dev-root-token-change-me";  # Use sops in prod!
    ui = true;
  };

  # ========================================================================
  # RUSTGUAC - Gateway centralisée (multi-protocole, OIDC, audit)
  # ========================================================================
  services.rustguac = {
    enable = true;
    host = "127.0.0.1";
    port = 8089;

    # TLS handled by nginx reverse proxy
    tls = null;

    # guacd connection
    guacd = {
      host = "127.0.0.1";
      port = 4822;
      tls = true;
    };

    # Vault for connections storage
    vault = {
      address = "http://127.0.0.1:8200";
      token = "rustguac-dev-root-token-change-me";  # Use sops!
      mountPath = "secret";
      connectionsPath = "rustguac/connections";
    };

    # OIDC (configure with your provider: Authentik, Keycloak, Google, Okta)
    oidc = {
      issuerUrl = "https://auth.example.com";  # YOUR OIDC PROVIDER
      clientId = "rustguac";
      clientSecret = "***";  # Use sops!
      redirectUrl = "https://guac.example.com/api/oidc/callback";
      scopes = [ "openid" "profile" "email" "groups" ];
      usernameClaim = "email";
      groupsClaim = "groups";
    };

    # API Keys as fallback (for agents/scripts)
    apiKeys = [
      {
        name = "ci-bot";
        keyHash = "sha256:...";  # echo -n "your-key" | sha256sum
        roles = [ "operator" ];
        ipAllowlist = [ "10.0.0.0/8" ];
      }
    ];

    # Session recording
    recording = {
      enable = true;
      storagePath = "/var/lib/rustguac/recordings";
      maxSize = "10G";
      maxAge = "30d";
    };

    rateLimit = {
      enabled = true;
      requestsPerMinute = 120;
    };
  };

  # ========================================================================
  # KASMVNC - Bureau personnel Wayland haute perf (LXQt + kwin_wayland)
  # ========================================================================
  services.kasmvnc = {
    enable = true;
    user = "marc";  # Your user
    display = ":1";
    geometry = "1920x1080";
    bindAddress = "127.0.0.1";  # Behind nginx
    port = 8443;  # Internal HTTPS port

    # TLS certs (use sops for private key!)
    tls = {
      certFile = "/run/secrets/kasmvnc-cert.pem";
      keyFile = "/run/secrets/kasmvnc-key.pem";
    };

    # Password file (generated by kasmvncpasswd)
    passwordFile = "/home/marc/.kasmpasswd";

    desktop = "lxqt-wayland";
    extraPackages = with pkgs; [
      firefox
      code
      gnome-terminal
    ];
  };

  # ========================================================================
  # RUSTDESK - P2P relay pour accès natif
  # ========================================================================
  services.rustdesk = {
    enable = true;
    hbbs = { enable = true; port = 21115; };
    hbbr = { enable = true; port = 21116; apiPort = 21118; };
    dashboard = { enable = true; port = 21114; };
    openFirewall = true;
  };

  # ========================================================================
  # NGINX - Reverse proxy avec ACME pour les deux services
  # ========================================================================
  services.nginx.rustguac = {
    enable = true;
    domain = "guac.example.com";  # YOUR DOMAIN
    upstream = "http://127.0.0.1:8089";
    acme = true;
    acmeEmail = "admin@example.com";
    websocket = true;
  };

  services.nginx.kasmvnc = {
    enable = true;
    domain = "kasm.example.com";  # YOUR DOMAIN
    upstream = "https://127.0.0.1:8443";
    acme = true;
    acmeEmail = "admin@example.com";
    websocket = true;
  };

  # ========================================================================
  # SECRETS (sops-nix) - À configurer dans ton flake
  # ========================================================================
  # sops.secrets = {
  #   rustguac-oidc-secret = { ... };
  #   vault-root-token = { ... };
  #   kasmvnc-tls-cert = { ... };
  #   kasmvnc-tls-key = { ... };
  #   rustguac-vault-token = { ... };
  # };

  # ========================================================================
  # USER LINGERING (pour systemd user services KasmVNC)
  # ========================================================================
  systemd.user.enable = true;
  systemd.user.lingerUsers = [ "marc" ];

  # ========================================================================
  # FIREWALL (ports additionnels si needed)
  # ========================================================================
  networking.firewall.allowedTCPPorts = [ 22 80 443 ];  # SSH, HTTP, HTTPS
  networking.firewall.allowedUDPPorts = [ ];  # WebRTC UDP handled by KasmVNC directly
}