"""Hermes Web UI -- API modules.

Patched entry point (see services/hermes-webui/core_title_adoption.py in the
NixOS flake): importing the package starts the core title adoption watchdog, so
the chat sidebar shows the session title already generated by the Hermes core
instead of the raw first message.  Remove this patch once the behaviour exists
upstream in the hermes-webui input.
"""

from . import core_title_adoption as _core_title_adoption

_core_title_adoption.start()