"""Adopt session titles already generated by the Hermes core.

Why this exists
---------------
The Hermes core (``agent/title_generator.py``) names a session a few seconds
after the first user message and persists that title in ``state.db`` with
``title_source='llm'``.

The WebUI keeps its own title in the session sidecar JSON and only writes it
when a run reaches ``done`` (``_run_background_title_update`` in
``api/streaming.py``).  Two consequences in the chat sidebar:

* for the whole duration of a run the row shows the deterministic placeholder,
  i.e. the truncated first user message, instead of a summary of the topic;
* when a run is interrupted or never reaches ``done``, the placeholder stays
  forever.

This watchdog closes that gap with no extra LLM call: every few seconds it
copies the title the core already generated into the WebUI sidecar, so the
sidebar shows a real title within seconds of the first message.

Behaviour and safety
--------------------
* Only sessions whose title is still automatic/provisional are touched.  A
  manual rename (``manual_title``) is never overwritten, and read-only imported
  sessions (CLI/TUI/gateway) are skipped: their title already comes from the
  core.
* Once adopted, the sidecar is marked ``llm_title_generated``, so the existing
  background title path skips it.  No duplicate generation, no extra spend.
* ``state.db`` is opened **read-only**; nothing is ever written back to it.
* Every pass is wrapped in try/except: a failure can never affect a run.

Disable with ``HERMES_WEBUI_CORE_TITLE_ADOPTION=0``.
"""

from __future__ import annotations

import json
import logging
import os
import sys
import threading
import time

logger = logging.getLogger(__name__)

# Poll cadence and startup delay (the server must be up and its modules
# importable before the first pass).
POLL_SECONDS = 20.0
START_DELAY_SECONDS = 15.0

# Index entries loaded per pass when the session is not already in memory.
# Bounded so a big transcript can never make the watchdog expensive.
INDEX_LOAD_LIMIT = 3
MAX_INDEX_FILE_BYTES = 2 * 1024 * 1024

_TITLE_SOURCE_LLM = "llm"
_MAX_TITLE_CHARS = 80

_started = False
_start_lock = threading.Lock()


def _enabled() -> bool:
    raw = os.getenv("HERMES_WEBUI_CORE_TITLE_ADOPTION", "1")
    return str(raw).strip().lower() not in ("0", "false", "no", "off")


def _placeholder_like(title: str) -> bool:
    return str(title or "").strip() in ("", "Untitled", "New Chat")


def _is_candidate(session) -> bool:
    """True when this session's title may be replaced by the core title."""
    if getattr(session, "manual_title", False):
        return False
    if getattr(session, "llm_title_generated", False):
        return False
    if getattr(session, "read_only", False):
        return False
    if getattr(session, "is_cli_session", False):
        return False
    return not _placeholder_like(getattr(session, "title", ""))


def _recent_index_candidate_ids(limit: int) -> list:
    """Ids from the sidebar index whose title is still provisional.

    Only used to pull sessions that are not in memory yet; the caller reloads
    them through ``get_session`` so the whole transcript is present before the
    sidecar is rewritten.
    """
    try:
        from api.config import SESSION_INDEX_FILE
    except Exception:
        return []
    try:
        if not SESSION_INDEX_FILE.exists():
            return []
        if SESSION_INDEX_FILE.stat().st_size > MAX_INDEX_FILE_BYTES:
            return []
        rows = json.loads(SESSION_INDEX_FILE.read_bytes())
    except Exception:
        return []
    out = []
    for row in rows if isinstance(rows, list) else []:
        try:
            if row.get("manual_title"):
                continue
            if _placeholder_like(row.get("title")):
                continue
            sid = row.get("session_id")
            if sid:
                out.append(str(sid))
        except Exception:
            continue
        if len(out) >= limit:
            break
    return out


def _open_core_db(profile):
    """Open the profile's ``state.db`` **read-only**, or None.

    Deliberately independent from ``api.state_sync`` (which needs a writable
    handle): this watchdog never writes to state.db, so it must not open one.
    """
    try:
        from hermes_state import SessionDB
    except Exception:
        return None
    try:
        from pathlib import Path

        if profile:
            from api.profiles import (
                _resolve_profile_home_for_name,
                _PROFILE_ID_RE,
                _is_root_profile,
            )

            if not (_is_root_profile(profile) or _PROFILE_ID_RE.fullmatch(profile)):
                return None
            home = Path(_resolve_profile_home_for_name(profile))
        else:
            from api.profiles import get_active_hermes_home

            home = Path(get_active_hermes_home())
        db_path = home.expanduser().resolve() / "state.db"
        if not db_path.exists():
            return None
        return SessionDB(db_path, read_only=True)
    except Exception:
        logger.debug("core title adoption: could not open state.db", exc_info=True)
        return None


def _adopt_once() -> int:
    """One pass: copy core titles into WebUI sidecars. Returns the count."""
    from api import session_events
    from api.config import LOCK, SESSIONS, _get_session_agent_lock
    from api.models import get_session

    with LOCK:
        ids = [sid for sid, s in SESSIONS.items() if _is_candidate(s)]

    # Sessions not in memory yet: load a few recent ones so their row can be
    # fixed too (bounded by INDEX_LOAD_LIMIT).
    for sid in _recent_index_candidate_ids(INDEX_LOAD_LIMIT):
        if sid in ids:
            continue
        with LOCK:
            if sid in SESSIONS:
                continue
        try:
            session = get_session(sid)
        except Exception:
            session = None
        if session is not None and _is_candidate(session):
            ids.append(sid)

    if not ids:
        return 0

    # Group by profile so each state.db is opened once.
    by_profile: dict = {}
    with LOCK:
        for sid in ids:
            s = SESSIONS.get(sid)
            if s is None:
                continue
            by_profile.setdefault(str(getattr(s, "profile", "") or ""), []).append(sid)

    adopted = 0
    for profile, sids in by_profile.items():
        db = _open_core_db(profile or None)
        if db is None:
            continue
        try:
            for sid in sids:
                with LOCK:
                    s = SESSIONS.get(sid)
                    if s is None or not _is_candidate(s):
                        continue
                try:
                    core_title = db.get_session_title(sid)
                    core_source = db.get_session_title_source(sid)
                except Exception:
                    continue
                core_title = str(core_title or "").strip()
                if not core_title:
                    continue
                if str(core_source or "").strip().lower() != _TITLE_SOURCE_LLM:
                    continue
                if str(s.title or "").strip() == core_title:
                    continue
                with _get_session_agent_lock(sid):
                    with LOCK:
                        s = SESSIONS.get(sid)
                        if s is None or not _is_candidate(s):
                            continue
                        s.title = core_title[:_MAX_TITLE_CHARS]
                        s.llm_title_generated = True
                        s.manual_title = False
                    # Session.save() takes the global LOCK internally: keep the
                    # per-session agent lock, release LOCK first (same pattern
                    # as the background title path in api/streaming.py).
                    s.save(touch_updated_at=False)
                adopted += 1
                logger.info(
                    "core title adoption: session=%s title=%r", sid, s.title
                )
                try:
                    session_events.publish_session_list_changed(
                        "core_title_adopted",
                        profile=getattr(s, "profile", None),
                        session_id=sid,
                    )
                except Exception:
                    logger.debug(
                        "core title adoption: sidebar notify failed for %s", sid
                    )
        finally:
            try:
                db.close()
            except Exception:
                pass
    return adopted


def _watchdog() -> None:
    time.sleep(START_DELAY_SECONDS)
    while True:
        try:
            if _enabled():
                count = _adopt_once()
                if count:
                    logger.info(
                        "core title adoption: adopted %d title(s) from state.db",
                        count,
                    )
        except Exception:
            logger.debug("core title adoption pass failed", exc_info=True)
        time.sleep(POLL_SECONDS)


def start() -> None:
    """Start the watchdog once, from the WebUI server process only."""
    prog = ""
    try:
        prog = os.path.basename(sys.argv[0] or "")
    except Exception:
        prog = ""
    # Sub-processes (code kernel runners, bootstrap helpers) must not spawn it.
    if prog and prog not in ("server.py", "bootstrap.py", "hermes-webui"):
        return
    global _started
    with _start_lock:
        if _started:
            return
        _started = True
    threading.Thread(
        target=_watchdog, name="core-title-adoption", daemon=True
    ).start()