# services/matrix-conduit/default.nix
# Conduit Matrix homeserver for deck (Steam Deck).
# Replaces Synapse on tower for matrix.marcpartensky.com.
# Uses rocksdb (embedded) for simplicity - no external PostgreSQL needed.
# Configures the nixpkgs services.matrix-conduit module and adds helper services.
{ config, pkgs, lib, inputs, ... }: let
  dataDir = "/var/lib/matrix-conduit";
  serverName = "matrix.marcpartensky.com";
in {
  # This module is imported when the user enables services.matrix-conduit.enable
  # It provides additional configuration on top of the nixpkgs module
  config = lib.mkIf config.services.matrix-conduit.enable {
    # Generate registration_token at first boot if not provided via config
    systemd.services.matrix-conduit-generate-token = {
      description = "Generate Conduit registration token on first boot";
      wantedBy = [ "multi-user.target" ];
      before = [ "matrix-conduit.service" ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        User = "root";
      };
      script = ''
        set -euo pipefail
        TOKEN_FILE="${dataDir}/registration_token"
        install -d -m 700 "${dataDir}"
        if [ ! -f "$TOKEN_FILE" ]; then
          ${pkgs.openssl}/bin/openssl rand -hex 32 > "$TOKEN_FILE"
          chmod 600 "$TOKEN_FILE"
          echo "Generated registration token at $TOKEN_FILE"
        fi
      '';
    };

    # Ensure Conduit starts after token generation
    systemd.services.matrix-conduit = {
      after = [ "matrix-conduit-generate-token.service" ];
      requires = [ "matrix-conduit-generate-token.service" ];
    };

    # Create Hermes bot account (@hermes:matrix.marcpartensky.com) on first boot
    systemd.services.matrix-conduit-register-hermes = {
      description = "Create Hermes bot account on Conduit";
      wantedBy = [ "multi-user.target" ];
      after = [ "matrix-conduit.service" ];
      requires = [ "matrix-conduit.service" ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        User = "root";
      };
      path = [
        pkgs.curl
        pkgs.jq
        pkgs.openssl
        pkgs.coreutils
      ];
      script = ''
        set -euo pipefail
        BASE_URL="http://127.0.0.1:6167"
        DATA_DIR="${dataDir}"
        PASS_FILE="''${DATA_DIR}/hermes-bot-password"
        TOKEN_FILE="/var/lib/hermes/.hermes/matrix-token"
        REG_TOKEN_FILE="''${DATA_DIR}/registration_token"

        umask 077
        install -d -m 700 "''${DATA_DIR}"

        # Generate/retrieve bot password
        if [ ! -f "$PASS_FILE" ]; then
          ${pkgs.openssl}/bin/openssl rand -hex 24 > "$PASS_FILE"
        fi
        PASS=$(cat "$PASS_FILE")

        # Read registration token (generated by matrix-conduit-generate-token)
        if [ ! -f "$REG_TOKEN_FILE" ]; then
          echo "Registration token not found at $REG_TOKEN_FILE"
          exit 1
        fi
        REG_TOKEN=$(cat "$REG_TOKEN_FILE")

        # Wait for Conduit to be ready
        for i in {1..30}; do
          if ${pkgs.curl}/bin/curl -sf "$BASE_URL/_matrix/client/versions" >/dev/null; then
            break
          fi
          sleep 1
        done

        # First try to login (account may already exist)
        for _ in 1 2 3 4 5; do
          RESP=$(${pkgs.curl}/bin/curl -sf -X POST \
            "$BASE_URL/_matrix/client/v3/login" \
            -H 'Content-Type: application/json' \
            -d '{\"type\":\"m.login.password\",\"identifier\":{\"type\":\"m.id.user\",\"user\":\"hermes\"},\"password\":\"'$PASS'\",\"initial_device_display_name\":\"Hermes Agent\"}') && break
          sleep 2
        done

        # If login failed, register using registration_token (Synapse-compatible admin API)
        if ! echo "$RESP" | ${pkgs.gnugrep}/bin/grep -q "access_token"; then
          NONCE=$(${pkgs.curl}/bin/curl -sf "$BASE_URL/_synapse/admin/v1/register" | ${pkgs.jq}/bin/jq -r .nonce)
          MAC=$(printf '%s\0%s\0%s\0%s' "$NONCE" "hermes" "$PASS" "admin" | ${pkgs.openssl}/bin/openssl dgst -sha1 -hmac "$REG_TOKEN" | awk '{print $NF}')
          ${pkgs.curl}/bin/curl -sf -X POST \
            "$BASE_URL/_synapse/admin/v1/register" \
            -H 'Content-Type: application/json' \
            -d "$(${pkgs.jq}/bin/jq -n --arg n "$NONCE" --arg u "hermes" --arg p "$PASS" --arg m "$MAC" '{nonce: $n, username: $u, password: $p, mac: $m, admin: false, inhibit_login: false}')" \
            || true
          sleep 1
          # Now login
          RESP=$(${pkgs.curl}/bin/curl -sf -X POST \
            "$BASE_URL/_matrix/client/v3/login" \
            -H 'Content-Type: application/json' \
            -d '{\"type\":\"m.login.password\",\"identifier\":{\"type\":\"m.id.user\",\"user\":\"hermes\"},\"password\":\"'$PASS'\",\"initial_device_display_name\":\"Hermes Agent\"}')
        fi

        # Extract and store access token
        TOKEN=$(printf '%s' "$RESP" | ${pkgs.gnugrep}/bin/grep -o '"access_token":"[^"]*"' | ${pkgs.coreutils}/bin/cut -d '"' -f4)
        if [ -n "$TOKEN" ] && [ "$TOKEN" != "null" ]; then
          ${pkgs.coreutils}/bin/mkdir -p /var/lib/hermes/.hermes
          printf '%s' "$TOKEN" > "$TOKEN_FILE"
          ${pkgs.coreutils}/bin/chown hermes:hermes "$TOKEN_FILE"
          ${pkgs.coreutils}/bin/chmod 600 "$TOKEN_FILE"
          echo "Hermes bot token stored at $TOKEN_FILE"
        else
          echo "Failed to obtain access token for @hermes"
          exit 1
        fi
      '';
    };

    # Create admin user (@hermes-admin) using registration_token
    systemd.services.matrix-conduit-create-admin = {
      description = "Create Conduit admin user @hermes-admin";
      wantedBy = [ "multi-user.target" ];
      after = [ "matrix-conduit.service" ];
      requires = [ "matrix-conduit.service" ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        User = "root";
      };
      path = [
        pkgs.curl
        pkgs.jq
        pkgs.openssl
        pkgs.coreutils
      ];
      script = ''
        set -euo pipefail
        BASE_URL="http://127.0.0.1:6167"
        DATA_DIR="${dataDir}"
        ADMIN_PASS_FILE="''${DATA_DIR}/hermes-admin-password"
        ADMIN_TOKEN_FILE="''${DATA_DIR}/hermes-admin-token"
        REG_TOKEN_FILE="''${DATA_DIR}/registration_token"

        umask 077
        install -d -m 700 "''${DATA_DIR}"

        # Read registration token
        if [ ! -f "$REG_TOKEN_FILE" ]; then
          echo "Registration token not found at $REG_TOKEN_FILE"
          exit 1
        fi
        REG_TOKEN=$(cat "$REG_TOKEN_FILE")

        # Wait for Conduit to be ready
        for i in {1..30}; do
          if ${pkgs.curl}/bin/curl -sf "$BASE_URL/_matrix/client/versions" >/dev/null; then
            break
          fi
          sleep 1
        done

        # Generate/retrieve admin password
        if [ ! -f "$ADMIN_PASS_FILE" ]; then
          ${pkgs.openssl}/bin/openssl rand -hex 24 > "$ADMIN_PASS_FILE"
        fi
        ADMIN_PASS=$(cat "$ADMIN_PASS_FILE")

        # Check if admin token already exists and is valid
        if [ -f "$ADMIN_TOKEN_FILE" ]; then
          EXISTING_TOKEN=$(cat "$ADMIN_TOKEN_FILE")
          CODE=$(${pkgs.curl}/bin/curl -s -o /dev/null -w '%{http_code}' \
            -H "Authorization: Bearer $EXISTING_TOKEN" \
            "$BASE_URL/_synapse/admin/v1/server_version" || true)
          if [ "$CODE" = "200" ]; then
            echo "Existing admin token is valid"
            exit 0
          fi
        fi

        # Register @hermes-admin using registration_token (Synapse-compatible admin API)
        NONCE=$(${pkgs.curl}/bin/curl -sf "$BASE_URL/_synapse/admin/v1/register" | ${pkgs.jq}/bin/jq -r .nonce)
        MAC=$(printf '%s\0%s\0%s\0%s' "$NONCE" "hermes-admin" "$ADMIN_PASS" "admin" | ${pkgs.openssl}/bin/openssl dgst -sha1 -hmac "$REG_TOKEN" | awk '{print $NF}')
        RESP=$(${pkgs.curl}/bin/curl -sf -X POST \
          "$BASE_URL/_synapse/admin/v1/register" \
          -H 'Content-Type: application/json' \
          -d "$(${pkgs.jq}/bin/jq -n --arg n "$NONCE" --arg u "hermes-admin" --arg p "$ADMIN_PASS" --arg m "$MAC" '{nonce: $n, username: $u, password: $p, mac: $m, admin: true, inhibit_login: false}')" || true)

        # If user exists, just login
        if ! echo "$RESP" | ${pkgs.gnugrep}/bin/grep -q "access_token"; then
          RESP=$(${pkgs.curl}/bin/curl -sf -X POST \
            "$BASE_URL/_matrix/client/v3/login" \
            -H 'Content-Type: application/json' \
            -d '{\"type\":\"m.login.password\",\"identifier\":{\"type\":\"m.id.user\",\"user\":\"hermes-admin\"},\"password\":\"'$ADMIN_PASS'\",\"device_id\":\"HERMESADMIN\"}')
        fi

        ADMIN_TOKEN=$(printf '%s' "$RESP" | ${pkgs.gnugrep}/bin/grep -o '"access_token":"[^"]*"' | ${pkgs.coreutils}/bin/cut -d '"' -f4)
        if [ -n "$ADMIN_TOKEN" ] && [ "$ADMIN_TOKEN" != "null" ]; then
          printf '%s' "$ADMIN_TOKEN" > "$ADMIN_TOKEN_FILE"
          chmod 600 "$ADMIN_TOKEN_FILE"
          echo "Admin token stored at $ADMIN_TOKEN_FILE"
        else
          echo "Failed to obtain admin token"
          exit 1
        fi
      '';
    };

    # Firewall: open federation port (8448) for inbound federation
    # Client API (8008/443) is handled by nginx/Pangolin
    networking.firewall.allowedTCPPorts = [
      8448
    ];
  };
}